# Config file for pipeline_bulkont.py
Author: Chen-Yi Wang

## general options

# Copyright statement

genome_fasta: "/project/cribbslab/shared/proj013/analyses/reference/Talon/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta"

# Please check the requirement before initiate the pipeline

#Requirement: 

### Load R: module load R-cbrg/

### Availability of the required R packages

gtf: "/project/cribbslab/shared/proj013/analyses/reference/wf-transcriptomes/hg38_gencode/gencode.v44.annotation.gtf"

bamdir: "mapped_files.dir"

annotation: "/project/cribbslab/shared/proj013/analyses/reference/wf-transcriptomes/hg38_gencode/gencode.v44.annotation.sqlite"



