
#########################################
#                                       #
# configuration file for pipeline_bambu #
# Author: Chen-Yi Wang                  #
# Latest update: Sep 10, 2024           #
#                                       #
#########################################

# This is a tool to process multiple bam files for transcript identification and discovery, using R package Bambu
# Input files: sorted bam files
# Output files: heatmap, pca plots and count matrices in Bambu_output  

# Please check the requirement before initiate the pipeline

#Requirement: 

### Load R: module load R-cbrg/
### Availability of the required R packages

gtf: "/project/cribbslab/shared/proj013/analyses/reference/wf-transcriptomes/hg38_gencode/gencode.v44.annotation.gtf"
genome: "/project/cribbslab/shared/proj013/analyses/reference/Talon/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta"
bam: path to bam files
